#!/usr/bin/env bash
# Claw Chat one-shot installer.
#
# Usage:
#   HOSTNAME=chat.example.com ALLOWED_EMAIL=me@example.com bash install.sh
#
# Optional env vars:
#   NEXT_PUBLIC_API_ORIGIN  (default: https://$HOSTNAME)
#   SESSION_SECRET          (default: auto-generated with openssl)
#   ALLOWED_ORIGINS         (default: https://$HOSTNAME)
#   APP_DIR                 (default: /opt/claw-chat)
#
# Idempotent — safe to re-run to pick up newly-issued SSL certs or
# apply env-var changes.

set -euo pipefail

: "${HOSTNAME:?HOSTNAME env var is required (e.g. chat.example.com)}"
: "${ALLOWED_EMAIL:?ALLOWED_EMAIL env var is required (single authorized user email)}"
: "${NEXT_PUBLIC_API_ORIGIN:=https://$HOSTNAME}"
: "${SESSION_SECRET:=$(openssl rand -hex 48 2>/dev/null || head -c 48 /dev/urandom | xxd -p | tr -d '\n')}"
: "${ALLOWED_ORIGINS:=https://$HOSTNAME}"
: "${APP_DIR:=/opt/claw-chat}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "== Claw Chat installer =="
echo "   Hostname: $HOSTNAME"
echo "   App dir:  $APP_DIR"
echo "   Email:    $ALLOWED_EMAIL"

# ── 1. Docker ──────────────────────────────────────────────────────────
if ! command -v docker >/dev/null 2>&1; then
  echo "-- Installing Docker..."
  curl -fsSL https://get.docker.com | sh
fi
if ! docker compose version >/dev/null 2>&1; then
  echo "!! 'docker compose' plugin not available. Install docker-compose-plugin and re-run." >&2
  exit 1
fi

# ── 2. Stop conflicting host nginx ─────────────────────────────────────
# The chat app's claw-nginx container binds host port 80 (and 443 when
# TLS is enabled). Any host-level nginx service must step aside.
sudo systemctl stop nginx 2>/dev/null || true
sudo systemctl disable nginx 2>/dev/null || true

# ── 3. Detect SSL certs ────────────────────────────────────────────────
CERT_SRC="/etc/letsencrypt/live/$HOSTNAME"
TLS_ENABLED=0
if [ -f "$CERT_SRC/fullchain.pem" ] && [ -f "$CERT_SRC/privkey.pem" ]; then
  TLS_ENABLED=1
  echo "-- TLS certs found at $CERT_SRC — enabling HTTPS"
else
  echo "-- No certs at $CERT_SRC — starting HTTP-only. Re-run after provisioning SSL."
fi

# ── 4. Write config ────────────────────────────────────────────────────
sudo mkdir -p "$APP_DIR" "$APP_DIR/nginx"

# .env
sudo tee "$APP_DIR/.env" >/dev/null <<EOF
# Generated by install.sh — edit docker compose env_file path to customise.
NEXT_PUBLIC_API_ORIGIN=$NEXT_PUBLIC_API_ORIGIN
ALLOWED_EMAIL=$ALLOWED_EMAIL
SESSION_SECRET=$SESSION_SECRET
ALLOWED_ORIGINS=$ALLOWED_ORIGINS
EOF

# docker-compose.yml — ports block + cert mount depend on TLS_ENABLED
if [ "$TLS_ENABLED" = "1" ]; then
  PORTS_BLOCK=$'      - "80:80"\n      - "443:443"'
  CERT_VOL=$'\n      - '"$CERT_SRC"':/etc/nginx/certs:ro'
else
  PORTS_BLOCK='      - "80:80"'
  CERT_VOL=''
fi

sudo tee "$APP_DIR/docker-compose.yml" >/dev/null <<EOF
# Generated by install.sh. Re-run the script to regenerate after env/cert changes.
services:
  claw-chat:
    image: teslicvukasin/claw-ops-chat:latest
    container_name: claw-chat
    env_file: .env
    volumes:
      - /root:/root
    expose:
      - "3100"
    init: true
    restart: unless-stopped
    cap_drop: [ALL]
    cap_add: [NET_BIND_SERVICE]
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://127.0.0.1:3100/chat/api/health"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 15s
    networks: [clawnet]

  nginx:
    image: nginx:1.27-alpine
    container_name: claw-nginx
    depends_on:
      claw-chat:
        condition: service_healthy
    ports:
$PORTS_BLOCK
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro$CERT_VOL
    restart: unless-stopped
    networks: [clawnet]

networks:
  clawnet:
    driver: bridge
EOF

# nginx/default.conf — pick http-only or https template, substitute hostname
if [ "$TLS_ENABLED" = "1" ]; then
  SRC_CONF="$SCRIPT_DIR/nginx/https.conf"
else
  SRC_CONF="$SCRIPT_DIR/nginx/http-only.conf"
fi
if [ ! -f "$SRC_CONF" ]; then
  echo "!! Template not found: $SRC_CONF" >&2
  echo "   Did you run this script from the prod-example directory?" >&2
  exit 1
fi
sudo sed "s|{{HOSTNAME}}|$HOSTNAME|g" "$SRC_CONF" \
  | sudo tee "$APP_DIR/nginx/default.conf" >/dev/null

# ── 5. Launch ──────────────────────────────────────────────────────────
cd "$APP_DIR"
echo "-- Pulling images..."
sudo docker compose pull
echo "-- Starting stack..."
sudo docker compose up -d

# ── 6. Wait for health ─────────────────────────────────────────────────
echo "-- Waiting for claw-chat to become healthy..."
for i in $(seq 1 30); do
  STATUS=$(sudo docker inspect --format='{{.State.Health.Status}}' claw-chat 2>/dev/null || echo "")
  if [ "$STATUS" = "healthy" ]; then
    echo ""
    echo "✓ claw-chat is healthy"
    if [ "$TLS_ENABLED" = "1" ]; then
      echo "  Open: https://$HOSTNAME/chat"
    else
      echo "  Open: http://$HOSTNAME/chat"
    fi
    echo "  First-time setup: sign in, then open Settings → Terminal and run 'claude auth login' to authenticate the Claude CLI."
    exit 0
  fi
  printf '.'
  sleep 2
done
echo ""
echo "!! claw-chat did not reach healthy within 60s." >&2
echo "   Check: sudo docker compose -f $APP_DIR/docker-compose.yml logs -f claw-chat" >&2
exit 1
